### ISSUE TITLE
[BUG][Fuzzer][ice-on-valid-code] Scalar cross-dtype `T.copy` (e.g. an `int64` index into an `int32` scratch) crashes with a `BufferStore` dtype-mismatch instead of casting

### ISSUE THREAD

**Issue by Hughshine** [tile-ai/tilelang#2689]
### Required prerequisites

- [x] I have read the documentation <https://tilelang.com>.
- [x] I have searched the Issue Tracker that this hasn't already been reported.

### What version of TileLang are you using?

0.1.12 (reproduced this session on the released `0.1.12` wheel; `copy_op.py` is byte-identical at the cited lines to `main` re-checked at `d36ec37c596ff8e587fc67fcf1e88bcb90cc60d6`).

### System information

NVIDIA L40S (`sm_89`), CUDA 13.0, Python 3.13, tilelang 0.1.12. The defect is in the target-independent Python `T.copy` frontend (the IR-build step), so it is not specific to one GPU (it aborts before any device code is generated).

### Problem description

A scalar single-element `T.copy(A[i], B[j])` between two *different* dtypes aborts at kernel-build time with an opaque `TypeError: dtype mismatch on BufferStore`, even though the general/collective `T.copy` of the same cross-dtype pair compiles and computes the correct conversion. The most natural way to hit it is an index-gather kernel: stashing an entry of an `int64` index array (torch's default dtype for `argsort`/`topk`/`randint().long()` results) into a small `int32` on-device scratch — `T.copy(indices[pid], idx[0])`. Same-dtype scalar `T.copy` compiles fine; the only difference in the failing case is that the two elements have different dtypes.

`T.copy` has a dedicated scalar path: when both sides are scalar `BufferLoad`s (a bare `[i]` index, no extent) it lowers straight to `dst[i] = src[i]` (docstring [`copy_op.py#L100-L101`](https://github.com/tile-ai/tilelang/blob/d36ec37c596ff8e587fc67fcf1e88bcb90cc60d6/tilelang/language/copy_op.py#L100-L101)). This path exists because the general `tl.tileop.copy` lowering builds its loop from the region extents and cannot handle an extent-less scalar load — so a scalar-index copy is routed to a direct `BufferStore` instead. But that direct store emits the source expression with no dtype conversion: the raw `int64` value is stored straight into the `int32` destination buffer, and the strict `BufferStore` constructor rejects the mismatch. The general path inserts the conversion (`Cast(dst->dtype, value)`), which is why the region form of the same cross-dtype copy compiles and the scalar path does not.

This is a regression: the cast-less scalar path was introduced later (see Provenance); before it, a scalar `BufferLoad` copy went through the general casting path, so a scalar cross-dtype `T.copy` lowered correctly.

### Reproducible example code

```python
import tilelang, tilelang.language as T, torch

N = 128

# ---------- TRIGGER: idiomatic gather-index copy, int64 index -> int32 scratch ----------
# `indices` is int64 (torch's default for argsort/topk/randint().long()); the kernel keeps
# an int32 on-device scratch. The scalar fast-path stores int64 straight into int32 -> crash.
@T.prim_func
def trigger(indices: T.Tensor((N,), "int64"), out: T.Tensor((N,), "int32")):
    with T.Kernel(N, threads=1) as pid:
        idx = T.alloc_local((1,), "int32")
        T.copy(indices[pid], idx[0])    # scalar fast-path: int64 -> int32, cast DROPPED
        out[pid] = idx[0]

tilelang.compile(trigger, target="cuda")   # -> TypeError: dtype mismatch on BufferStore (int32 = int64)

# ---------- CONTROL: the same copy as a 1-element region takes the casting path and computes ----------
@T.prim_func
def control(indices: T.Tensor((N,), "int64"), out: T.Tensor((N,), "int32")):
    with T.Kernel(N, threads=1) as pid:
        idx = T.alloc_local((1,), "int32")
        T.copy(indices[pid:pid + 1], idx[0:1])   # region copy -> tl.tileop.copy inserts the cast
        out[pid] = idx[0]

f = tilelang.compile(control, target="cuda")
ind = torch.randint(0, 1_000_000, (N,), dtype=torch.int64, device="cuda")
print(torch.equal(f(ind), ind.to(torch.int32)))   # -> True  (region path narrows int64->int32 correctly)
```

### Traceback

```
[TileLang:...builder:CRITICAL] (builder.py:1308): Failed to build prim_func from trigger
  File ".../tilelang/language/copy_op.py", line 112, in copy
    return tirx.BufferStore(dst.buffer, src, dst.indices)
  File ".../tvm/tirx/stmt.py", line 273, in __init__
  ...
  File ".../3rdparty/tvm/src/tirx/ir/stmt.cc", line 401, in tvm::tirx::BufferStore::BufferStore(...)
TypeError: dtype mismatch on BufferStore: buffer's dtype is `int32`, the lanes of indexing are: `1`, the scalability is: `0`, but RHS's dtype is `int64`
```

### Expected behavior

A scalar single-element `T.copy` between different dtypes should behave like the general copy path already does over the same cross-dtype pair: insert the dtype conversion and store the converted value (the `int64 -> int32` narrowing the collective copy computes — verified: the 1-element region control returns exactly `indices.to(int32)`). Since cross-dtype `T.copy` is an accepted, computable operation on the general path, the scalar fast path aborting on it is the problem. If cross-dtype scalar copy were instead meant to be unsupported, a clear frontend rejection would be preferable to the opaque internal `BufferStore` `TypeError`.

### Additional context

**Root cause.** The scalar-index path in `T.copy` stores the source value straight into the destination without the dtype conversion the general copy path applies, so a valid cross-dtype element copy aborts instead of compiling. This path exists for a real reason — the general `tl.tileop.copy` lowering derives its loop from the region extents ([`copy.cc` `MakeIterVars`](https://github.com/tile-ai/tilelang/blob/d36ec37c596ff8e587fc67fcf1e88bcb90cc60d6/src/op/copy.cc#L303-L337)) and cannot handle an extent-less scalar load, so a scalar-index copy is deliberately routed to a direct store. But that reroute copied the general path's *store* and omitted its *convert*: [`_normalize_copy_regions` returns both scalar `BufferLoad`s unchanged](https://github.com/tile-ai/tilelang/blob/d36ec37c596ff8e587fc67fcf1e88bcb90cc60d6/tilelang/language/copy_op.py#L30-L36), then [`copy()` emits `tirx.BufferStore(dst.buffer, src, dst.indices)`](https://github.com/tile-ai/tilelang/blob/d36ec37c596ff8e587fc67fcf1e88bcb90cc60d6/tilelang/language/copy_op.py#L111-L112) with the raw source expression and no cast — whereas the general path inserts [`value = Cast(dst->dtype, value)`](https://github.com/tile-ai/tilelang/blob/d36ec37c596ff8e587fc67fcf1e88bcb90cc60d6/src/op/copy.cc#L483) before its store.

**Suggested fix (proposed, not built).** In the scalar fast path, when `src.dtype != dst.buffer.dtype`, wrap the source in a cast to the destination dtype before constructing the `BufferStore`, so the fast path applies the same conversion the general `tl.tileop.copy` path already performs and produces the same result as the collective copy rather than a mismatched store.

**Distinct from existing issues.** Not #2610 (`[BUG][Fuzzer][ice-on-valid-code]` scalar `T.cast`) — that is a *different op* whose root is in the CUDA codegen conversion-intrinsic selection and which leaks an `nvcc` error for only two exotic dtype pairs at codegen time; this crashes at the frontend IR-build step for any dtype-mismatched scalar `T.copy`. Not #2616 (`[BUG][Fuzzer][wrong-code]` `DecoupleTypeCast`) — a C++ pass with a silent wrong-code lane-clobber, a different file, mechanism, and symptom. Not #187 (closed/fixed, "Copying scalar to output causes compilation error") — a different, already-fixed crash in an older copy path; same-dtype scalar copy now compiles cleanly. I searched the open and closed tracker and found no existing report of this cast-drop.

**Provenance.** The cast-less scalar `BufferStore` path was introduced by [#946](https://github.com/tile-ai/tilelang/pull/946) (`c61971e86a`, 2025-10-07), titled "Support Copy for Buffer Load with scalar indices" — it added scalar-index copy support (previously an extent-less scalar load hit an assertion in the region path) by routing to `return tir.BufferStore(dst.buffer, src, dst.indices)`, but without carrying over the general path's `Cast`. Before #946, `copy()` had no scalar path and scalar `BufferLoad`s went through the general (casting) copy-region path, so a scalar cross-dtype copy lowered correctly — this is therefore a regression introduced by #946. Later PRs only relocated it (#1887) and did the mechanical `tir.` -> `tirx.` rename (#2216).

**Reach.** The trigger requires a scalar single-element `T.copy` (both sides a bare `[i]` index, no slice) whose two elements have *different* dtypes. The scalar-element form itself is a documented, shipped shape: `testing/python/language/test_tilelang_language_copy.py:106` writes exactly `T.copy(indices[pid], idx[0])` in an index-gather kernel — it stays green only because the test author declared `indices` as `int32` (matching the `int32` scratch). The same idiom with an `int64` index array — torch's default dtype for `argsort`/`topk`/`randint().long()` results, and used across the shipped examples (e.g. the `dsa_sparse_finetune` gather kernels feed `topk_indices.to(torch.int64)`) — trips the crash. Same-dtype scalar `T.copy` compiles and runs correctly (verified this session), so the crash is the intersection of the scalar single-element form with a dtype mismatch; the reachable normal case is an `int64` index copied into an `int32` on-device scratch.
