### ISSUE TITLE
[BUG] Scalar variable incorrectly vectorized in T.Parallel loop (regression in 0.1.7.post1)

### ISSUE THREAD

**Issue by WXY277** [tile-ai/tilelang#1549]
### Required prerequisites

- [x] I have read the documentation <https://tilelang.com>.
- [x] I have searched the [Issue Tracker](https://github.com/tile-ai/tilelang/issues) that this hasn't already been reported. (comment there if it has.)

### What version of TileLang are you using?

0.1.7.post1

### System information

torch      2.5.0+cu121

### Problem description

Pre-allocated scalar variables using `T.alloc_var()` are incorrectly treated as arrays when assigned inside `T.Parallel` loops, causing compilation errors.  This is a regression from 0.1.6.post2 where the same code works correctly.

### Reproducible example code

The Python snippets:

```import torch
import tilelang
import tilelang.language as T

@tilelang.jit(
    pass_configs={
        tilelang.PassConfigKey.TL_DISABLE_TMA_LOWER: True,
        tilelang.PassConfigKey.TL_DISABLE_WARP_SPECIALIZED: True,
    },
)
def minimal_repro_kernel(
    batch:  int,
    seq_len:  int,
    feature_dim: int,
    BLOCK_SIZE: int = 16,
    num_threads: int = 64,
):
    
    INT32 = "int32"
    data_shape = [batch, seq_len, feature_dim]

    @T.prim_func
    def kernel_func(
        DataIn: T. Tensor(data_shape, INT32),
        DataOut: T.Tensor(data_shape, INT32),
    ):
        with T. Kernel(
            tilelang.cdiv(seq_len, BLOCK_SIZE), 
            batch, 
            threads=num_threads
        ) as (bx, bz):
            i_b = bz
            base_l = bx * BLOCK_SIZE

            shared_mem = T.alloc_shared([BLOCK_SIZE, feature_dim], dtype=INT32)

            # Load data to shared memory
            for l_idx, k in T.Parallel(BLOCK_SIZE, feature_dim):
                lq = base_l + l_idx
                if lq < seq_len:
                    shared_mem[l_idx, k] = DataIn[i_b, lq, k]
                else:
                    shared_mem[l_idx, k] = 0
            T.sync_threads()

            # Pre-allocated scalar variables (causes issue in 0.1.7.post1)
            idx = T.alloc_var(INT32)
            val_a = T.alloc_var(INT32)
            val_b = T.alloc_var(INT32)
            temp = T.alloc_var(INT32)

            # Process data with scalar variable assignments in parallel loop
            for l_idx, k in T.Parallel(BLOCK_SIZE, feature_dim):
                lq = base_l + l_idx
                if lq < seq_len:
                    idx = k  # Assignment to pre-allocated scalar in parallel loop
                    val_a = shared_mem[l_idx, idx]
                    
                    if idx + 1 < feature_dim: 
                        val_b = shared_mem[l_idx, idx + 1]
                    else:
                        val_b = 0
                    
                    # Simple computation
                    if val_a > val_b:
                        temp = val_a
                    else:
                        temp = val_b
                    
                    shared_mem[l_idx, idx] = temp
            T.sync_threads()

            # Write back
            for l_idx, k in T.Parallel(BLOCK_SIZE, feature_dim):
                lq = base_l + l_idx
                if lq < seq_len:
                    DataOut[i_b, lq, k] = shared_mem[l_idx, k]

    return kernel_func


if __name__ == "__main__": 
    import torch
    
    # Test parameters
    batch = 2
    seq_len = 32
    feature_dim = 16
    
    # Create test data
    data_in = torch.randint(0, 100, (batch, seq_len, feature_dim), dtype=torch.int32, device="cuda")
    data_out = torch.zeros_like(data_in)
    
    print("Testing minimal reproduction case...")
    print(f"tilelang version: {tilelang.__version__}")
    
    try:
        # This should work in 0.1.6.post2 but fail in 0.1.7.post1
        kernel = minimal_repro_kernel(batch, seq_len, feature_dim)
        kernel(data_in, data_out)
        print("✓ Kernel executed successfully")
    except RuntimeError as e:
        print("✗ Compilation failed with error:")
        if "expression must have pointer-to-object type" in str(e):
            print("\nThis is the expected bug:  scalar variable treated as array in vectorized code")
            print("Error snippet:", str(e).split("error: ")[1].split("\n")[0] if "error:" in str(e) else "")
        raise

```

### Traceback

```pytb
/tmp/tmp0r23qzdx/tvm_kernels.cu(23): error: expression must have pointer-to-object type but it has type "int"
        idx[v_.x] = v__1.x;
            ^

/tmp/tmp0r23qzdx/tvm_kernels.cu(24): error: expression must have pointer-to-object type but it has type "int"
        idx[v_.y] = v__1.y;
            ^

/tmp/tmp0r23qzdx/tvm_kernels.cu(25): error: expression must have pointer-to-object type but it has type "int"
        idx[v_.z] = v__1.z;
            ^

/tmp/tmp0r23qzdx/tvm_kernels.cu(26): error: expression must have pointer-to-object type but it has type "int"
        idx[v_.w] = v__1.w;
            ^

4 errors detected in the compilation of "/tmp/tmp0r23qzdx/tvm_kernels.cu".
```

### Expected behavior

The code should compile and run as it did in 0.1.6.post2.

**Comment by LeiWang1999** [comment]
@WXY277 Thanks for your report! yes it's an known bug and has been fixed with #1541 .. We'll release post2 for this issue next week. For now I think we can use nightly build or build from source as a workaround.

**Comment by WXY277** [comment]
@LeiWang1999 So many thanks!

**Comment by WXY277** [comment]
I tried the nightly builds and still see the bug. Short summary of my tests:
tilelang 0.1.6.post2 — works (kernel executed successfully)
tilelang 0.1.7.post1 — fails with the same compilation error
tilelang 0.1.7.post1+cu128.gitd70cf363 — also fails

Relevant log excerpts:

tilelang version: 0.1.6.post2
2025-12-28 11:56:17  [TileLang:tilelang.jit.kernel:INFO]: TileLang begins to compile kernel `kernel_func` with `out_idx=None`
2025-12-28 11:56:25  [TileLang:tilelang.jit.kernel:INFO]: TileLang completes to compile kernel `kernel_func`
✓ Kernel executed successfully

tilelang version: 0.1.7.post1
2025-12-28 11:51:23  [TileLang:tilelang.jit.kernel:INFO]: TileLang begins to compile kernel `kernel_func` with `out_idx=None`
✗ Compilation failed with error:
This is the expected bug:  scalar variable treated as array in vectorized code
Error snippet: expression must have pointer-to-object type but it has type "int"

tilelang version: 0.1.7.post1+cu128.gitd70cf363
2025-12-28 11:54:30  [TileLang:tilelang.jit.kernel:INFO]: TileLang begins to compile kernel `kernel_func` with `out_idx=None`
✗ Compilation failed with error:
This is the expected bug:  scalar variable treated as array in vectorized code
Error snippet: expression must have pointer-to-object type but it has type "int"

Is the fix from #1541 included in the 0.1.7.post1/nightly builds I tried?

**Comment by SiriusNEO** [comment]
Hi @WXY277, I make a smaller reproduction as followed:

```python
import tilelang
import tilelang.language as T

@tilelang.jit(
    pass_configs={
        tilelang.PassConfigKey.TL_DISABLE_TMA_LOWER: True,
        tilelang.PassConfigKey.TL_DISABLE_WARP_SPECIALIZED: True,
    },
)
def minimal_repro_kernel(siz: int):
    @T.prim_func
    def kernel_func(
        Data: T.Tensor((siz,), T.int32),
    ):
        with T. Kernel(1, threads=128) as _:
            # Pre-allocated scalar variables (causes issue in 0.1.7.post1)
            idx = T.alloc_var(T.int32)
            for i in T.Parallel(siz):
                idx = i
                Data[i] = idx

    return kernel_func


if __name__ == "__main__":
    import torch

    siz = 2048

    # Create test data
    data = torch.randint(0, 100, (siz,), dtype=torch.int32, device="cuda")

    print("Testing minimal reproduction case...")
    print(f"tilelang version: {tilelang.__version__}")

    try:
        # This should work in 0.1.6.post2 but fail in 0.1.7.post1
        kernel = minimal_repro_kernel(siz)
        kernel(data)
        print(kernel.get_kernel_source())
    except RuntimeError as e:
        print("✗ Compilation failed with error:")
        if "expression must have pointer-to-object type" in str(e):
            print("\nThis is the expected bug:  scalar variable treated as array in vectorized code")
            print("Error snippet:", str(e).split("error: ")[1].split("\n")[0] if "error:" in str(e) else "")
        raise
``` 

And after we dig into this issue, we find that it's not a regression. This error will not happen in 0.1.6.post2 probably because previous LayoutInference is not properly working so it's not revealed. 
If you change `alloc_var` to `alloc_local`:

```python
idx = T.alloc_local((1,), T.int32)
for i in T.Parallel(siz):
    idx[0] = i
    Data[i] = idx[0]
```

you will find the compilation is successful but the generated CUDA code is also strange (I'm not sure if it's the expected code you want).

```c++
extern "C" __global__ void __launch_bounds__(128, 1) kernel_func_kernel(int* __restrict__ Data) {
  int idx[1];
  for (int i = 0; i < 512; ++i) {
      int4 v_ = make_int4(0, 0, 0, 0);
      int4 v__1 = make_int4(((i * 4))+(1*0), ((i * 4))+(1*1), ((i * 4))+(1*2), ((i * 4))+(1*3));
      idx[v_.x] = v__1.x;
      idx[v_.y] = v__1.y;
      idx[v_.z] = v__1.z;
      idx[v_.w] = v__1.w;
    *(int4*)(Data + (i * 4)) = make_int4(idx[0], idx[0], idx[0], idx[0]);
  }
}
```

So the core problem is that we don't encourage to use local/var in a `T.Parallel` loop. If you want a thread-level operation, you may want to use `T.serial` / `T.vectorize`. We can discuss what is your expected behaviour of this codegen.

**Comment by SiriusNEO** [comment]
Updated: I use 0.1.6.post2 to compile your code. @WXY277 I'm not sure if this is the expected code you need.

```c++
extern "C" __global__ void __launch_bounds__(64, 1) kernel_func_kernel(int* __restrict__ DataIn, int* __restrict__ DataOut) {
  extern __shared__ __align__(1024) int shared_mem[];
  int idx = 0;
  int val_a = 0;
  int val_b = 0;
  int temp = 0;
  *(int4*)(shared_mem + (((int)threadIdx.x) * 4)) = *(int4*)(DataIn + (((((int)blockIdx.y) * 512) + (((int)blockIdx.x) * 256)) + (((int)threadIdx.x) * 4)));
  __syncthreads();
  #pragma unroll
  for (int i = 0; i < 4; ++i) {
    idx = (((int)threadIdx.x) & 15);
    val_a = shared_mem[(((((int64_t)i) * (int64_t)64) + ((((int64_t)((int)threadIdx.x)) >> (int64_t)4) * (int64_t)16)) + ((int64_t)idx))];
    __syncthreads();
    if (idx < 15) {
      val_b = shared_mem[((((i * 64) + ((((int)threadIdx.x) >> 4) * 16)) + idx) + 1)];
    } else {
      val_b = 0;
    }
    if (val_b < val_a) {
      temp = val_a;
    } else {
      temp = val_b;
    }
    __syncthreads();
    shared_mem[(((((int64_t)i) * (int64_t)64) + ((((int64_t)((int)threadIdx.x)) >> (int64_t)4) * (int64_t)16)) + ((int64_t)idx))] = temp;
  }
  __syncthreads();
  *(int4*)(DataOut + (((((int)blockIdx.y) * 512) + (((int)blockIdx.x) * 256)) + (((int)threadIdx.x) * 4))) = *(int4*)(shared_mem + (((int)threadIdx.x) * 4));
}
```

**Comment by WXY277** [comment]
@SiriusNEO  Thanks for your reply!  I didn't change `alloc_var` to `alloc_local`. Instead, after deleting some `alloc_var` variable definitions, the program no longer throws errors in version 0.1.7.post1 and 0.1.7.post2.
