### ISSUE TITLE
[Bug] test_storage_rewrite_detect_inplace_toggle unnecessarily triggers NVCC device compilation

### ISSUE THREAD

**Issue by jjjxia** [tile-ai/tilelang#2351]
## Bug description

`testing/python/components/test_storage_rewrite_detect_inplace.py::test_storage_rewrite_detect_inplace_toggle` is a source-codegen regression test for `TL_STORAGE_REWRITE_DETECT_INPLACE`, but it currently obtains the CUDA source through the default JIT path:

```python
kernel = _compile_kernel_without_inplace()
source = kernel.get_kernel_source()
```

Because the default execution backend is `tvm_ffi`, this path can trigger full device compilation with NVCC before returning the kernel source. That makes the test depend on the local CUDA compiler/toolkit setup even though the assertion only needs generated source text.

## Reproduction

On a checkout with a CUDA toolkit/header mismatch, run:

```bash
python -m pytest testing/python/components/test_storage_rewrite_detect_inplace.py -q
```

The test fails during NVCC compilation before reaching the source assertions.

Example failure:

```text
RuntimeError: ...
/home/.../nvidia/cu13/include/cccl/cuda/std/__cccl/cuda_toolkit.h:41:8: error: #error "CUDA compiler and CUDA toolkit headers are incompatible, please check your include paths"
Command: .../nvidia/cu13/bin/nvcc --cubin ...
```

## Expected behavior

This test should only exercise CUDA source generation and the storage-rewrite pass config toggle. It should not require successful cubin/device compilation.

## Actual behavior

The test takes the default JIT/`tvm_ffi` path, which enables host codegen and device compilation. Environment/toolchain failures can mask the behavior the test is supposed to validate.

## Context

The test is related to the `T.alloc_var` variable-reuse behavior from #994 and the `TL_STORAGE_REWRITE_DETECT_INPLACE` pass config introduced in #1089. The issue here is not the storage-rewrite semantics themselves; it is that the regression test is coupled to device compilation even though it only asserts on source code.

## Possible fix

Generate the source via lowering directly, under the relevant `PassContext`, for example:

```python
kernel = _compile_kernel_with_inplace if detect_inplace else _compile_kernel_without_inplace
pass_configs = {}
if detect_inplace:
    pass_configs[tilelang.PassConfigKey.TL_STORAGE_REWRITE_DETECT_INPLACE] = True
with tvm.transform.PassContext(config=pass_configs):
    artifact = tilelang.lower(kernel.get_tir(), target="cuda")
return artifact.kernel_source
```

This keeps the same source assertions while avoiding unnecessary NVCC device compilation.
