### ISSUE TITLE
AttributeError: 'JITKernel' object has no attribute 'func'

### ISSUE THREAD

**Issue by chesterout** [tile-ai/tilelang#353]
求问如下问题：

Traceback (most recent call last):
  File "/media/nvme/sglang2/tilelang/examples/deepseek_mla/benchmark_mla.py", line 606, in <module>
    perf = compare_a(target, shape["b"], shape["s_q"], shape["cache_seqlens"],
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/nvme/sglang2/tilelang/examples/deepseek_mla/benchmark_mla.py", line 545, in compare_a
    out_b, lse_b, perf_b = target_func(q, block_table, blocked_k, max_seqlen_pad, block_size, b,
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/nvme/anaconda/envs/sglang-test/lib/python3.12/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/media/nvme/sglang2/tilelang/examples/deepseek_mla/benchmark_mla.py", line 458, in run_flash_mla_tilelang
    out_flash = flash_mla_tilelang()
                ^^^^^^^^^^^^^^^^^^^^
  File "/media/nvme/sglang2/tilelang/examples/deepseek_mla/benchmark_mla.py", line 446, in flash_mla_tilelang
    out = kernel.func(
          ^^^^^^^^^^^
AttributeError: 'JITKernel' object has no attribute 'func'

**Comment by LeiWang1999** [comment]
@chesterout Thanks for your report! would you mind provide more details such as your tilelang version and device information? I guess it's sth due to tilelang version, you can checkout the nightly build:

```bash
pip install tilelang -f https://tile-ai.github.io/whl/nightly/cu121/
# or pip install tilelang --find-links https://tile-ai.github.io/whl/nightly/cu121/
```

**Comment by chesterout** [comment]
@LeiWang1999  the same problem occurs after reinstalling by pip install tilelang -f https://tile-ai.github.io/whl/nightly/cu121/

The device is H20, cuda is 12.8:
Cuda compilation tools, release 12.8, V12.8.93
Build cuda_12.8.r12.8/compiler.35583870_0

---------------------------------------------
Traceback (most recent call last):
  File "/media/nvme/sglang2/tilelang/examples/deepseek_mla/benchmark_mla.py", line 606, in <module>
    perf = compare_a(target, shape["b"], shape["s_q"], shape["cache_seqlens"],
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/nvme/sglang2/tilelang/examples/deepseek_mla/benchmark_mla.py", line 545, in compare_a
    out_b, lse_b, perf_b = target_func(q, block_table, blocked_k, max_seqlen_pad, block_size, b,
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/nvme/anaconda/envs/sglang312/lib/python3.12/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/media/nvme/sglang2/tilelang/examples/deepseek_mla/benchmark_mla.py", line 458, in run_flash_mla_tilelang
    out_flash = flash_mla_tilelang()
                ^^^^^^^^^^^^^^^^^^^^
  File "/media/nvme/sglang2/tilelang/examples/deepseek_mla/benchmark_mla.py", line 446, in flash_mla_tilelang
    out = kernel.func(
          ^^^^^^^^^^^
AttributeError: 'JITKernel' object has no attribute 'func'

**Comment by LeiWang1999** [comment]
@chesterout I see, likely due to the recent changes of interface, we should replace `kernel.func(*args)` with `kernel(*args)`

**Comment by LeiWang1999** [comment]
would you mind send a simple pr to fix if it works?

**Comment by chesterout** [comment]
@LeiWang1999, this works when the mean-seqlens==1151, while error when mean-seqlen==2175:

tilelang: b=128, s_q=1, mean_seqlens=1151.0, h_q=128, h_kv=1, d=576, dv=512, causal=True, dtype=torch.float16
perf tilelang: 0.475 ms, 86 TFLOPS, 432 GB/s
tilelang: b=128, s_q=1, mean_seqlens=2175.0, h_q=128, h_kv=1, d=576, dv=512, causal=True, dtype=torch.float16
gcc: fatal error: cannot execute 'cc1plus': execvp: No such file or directory
compilation terminated.
nvcc fatal   : Failed to preprocess host compiler properties.
Traceback (most recent call last):
  File "/media/nvme/sglang2/tilelang/examples/deepseek_mla/benchmark_mla.py", line 606, in <module>
    perf = compare_a(target, shape["b"], shape["s_q"], shape["cache_seqlens"],
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/nvme/sglang2/tilelang/examples/deepseek_mla/benchmark_mla.py", line 545, in compare_a
    out_b, lse_b, perf_b = target_func(q, block_table, blocked_k, max_seqlen_pad, block_size, b,
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/nvme/anaconda/envs/sglang312/lib/python3.12/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/media/nvme/sglang2/tilelang/examples/deepseek_mla/benchmark_mla.py", line 443, in run_flash_mla_tilelang
    kernel = tilelang.compile(program, out_idx=[8])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/nvme/anaconda/envs/sglang312/lib/python3.12/site-packages/tilelang/jit/__init__.py", line 144, in compile
    return cached(
           ^^^^^^^
  File "/media/nvme/anaconda/envs/sglang312/lib/python3.12/site-packages/tilelang/cache/__init__.py", line 29, in cached
    return _kernel_cache_instance.cached(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/nvme/anaconda/envs/sglang312/lib/python3.12/site-packages/tilelang/cache/kernel_cache.py", line 156, in cached
    kernel = JITKernel(
             ^^^^^^^^^^
  File "/media/nvme/anaconda/envs/sglang312/lib/python3.12/site-packages/tilelang/jit/kernel.py", line 109, in __init__
    adapter = self._compile_and_create_adapter(func, out_idx)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/nvme/anaconda/envs/sglang312/lib/python3.12/site-packages/tilelang/jit/kernel.py", line 226, in _compile_and_create_adapter
    adapter = CythonKernelAdapter(
              ^^^^^^^^^^^^^^^^^^^^
  File "/media/nvme/anaconda/envs/sglang312/lib/python3.12/site-packages/tilelang/jit/adapter/cython/adapter.py", line 205, in __init__
    self.lib_generator.compile_lib()
  File "/media/nvme/anaconda/envs/sglang312/lib/python3.12/site-packages/tilelang/jit/adapter/libgen.py", line 107, in compile_lib
    raise RuntimeError(f"Compilation Failed! {command}")
RuntimeError: Compilation Failed! ['nvcc', '-std=c++17', '-w', '-Xcudafe', '--diag_suppress=177', '--compiler-options', "'-fPIC'", '-lineinfo', '--shared', '/tmp/tmprey6g9lp.cu', '-lcuda', '-gencode', 'arch=compute_90a,code=sm_90a', '-I/media/nvme/anaconda/envs/sglang312/lib/python3.12/site-packages/tilelang/3rdparty/cutlass/include', '-I/media/nvme/anaconda/envs/sglang312/lib/python3.12/site-packages/tilelang/src', '-o', '/tmp/tmprey6g9lp.so']

**Comment by LeiWang1999** [comment]
@chesterout This is a strange issue — it says cc1plus is missing, but if that’s the case, the first config should have failed too. Are you running the experiment on an H100? I can try to reproduce it on my side.

**Comment by chesterout** [comment]
@LeiWang1999  
The device is H20, cuda is 12.8:
Cuda compilation tools, release 12.8, V12.8.93
Build cuda_12.8.r12.8/compiler.35583870_0

**Comment by LeiWang1999** [comment]
@chesterout works on my h100 with cuda 12.8

```python
(lei) (base) aiscuser@node-0:~/lei/tilelang$ /home/aiscuser/miniconda3/envs/lei/bin/python /home/aiscuser/lei/tilelang/examples/deepseek_mla/benchmark_mla.py --one
tilelang: b=128, s_q=1, mean_seqlens=1151.0, h_q=128, h_kv=1, d=576, dv=512, causal=True, dtype=torch.float16
perf tilelang: 0.141 ms, 290 TFLOPS, 1452 GB/s
tilelang: b=128, s_q=1, mean_seqlens=2175.0, h_q=128, h_kv=1, d=576, dv=512, causal=True, dtype=torch.float16
perf tilelang: 0.234 ms, 332 TFLOPS, 1526 GB/s
tilelang: b=128, s_q=1, mean_seqlens=4223.0, h_q=128, h_kv=1, d=576, dv=512, causal=True, dtype=torch.float16
```

**Comment by chesterout** [comment]
> [@chesterout](https://github.com/chesterout) This is a strange issue — it says cc1plus is missing, but if that’s the case, the first config should have failed too. Are you running the experiment on an H100? I can try to reproduce it on my side.

This is super weird, when I install tilelang on another H20 with "pip install tilelang -f https://tile-ai.github.io/whl/nightly/cu121/", everything works fine

**Comment by LeiWang1999** [comment]
maybe sth related to the environment
